In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
print(3*np.arange(9).reshape(3,3))

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


In [4]:
A = np.array([[1,4],[2,5],[3,6]])
A

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
B = np.array([[1,0],[0,1],[0,0]])

In [6]:
B

array([[1, 0],
       [0, 1],
       [0, 0]])

In [15]:
AB = np.dot(A.T,B)
AB

array([[1, 2],
       [4, 5]])

In [23]:
new = np.array([[1,-1],[1,-1]])
new

array([[ 1, -1],
       [ 1, -1]])

In [24]:
np.concatenate((AB, new), axis=1)

array([[ 1,  2,  1, -1],
       [ 4,  5,  1, -1]])

In [44]:
X = np.random.random((3,3))
X

array([[0.5069518 , 0.89308615, 0.21862921],
       [0.22433728, 0.12727185, 0.84457017],
       [0.34706296, 0.55906741, 0.89172283]])

In [45]:
C = (X>=0.5)
C

array([[ True,  True, False],
       [False, False,  True],
       [False,  True,  True]])

In [48]:
X[C] = -1
X

array([[-1.        , -1.        ,  0.21862921],
       [ 0.22433728,  0.12727185, -1.        ],
       [ 0.34706296, -1.        , -1.        ]])

In [39]:
C = np.zeros(9)
for i in range(len(X)):
    if X[i] < 0.5:
        C[i] = 0
    else:
        C[i] = 1
        X[i] = -1
            

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [12]:
C.reshape(3,3)

array([[0., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.]])

In [13]:
X.reshape(3,3)

array([[ 0.08498772, -1.        ,  0.17118492],
       [-1.        ,  0.02698453, -1.        ],
       [ 0.34082125, -1.        ,  0.04436695]])